# Generated by Django 4.2.2 on 2024-02-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("country_code", models.CharField(max_length=10)),
                ("coordinate", models.CharField(max_length=30)),
                ("temperature", models.FloatField()),
                ("pressure", models.IntegerField()),
                ("humidity", models.IntegerField()),
            ],
        ),
    ]
