# Generated by Django 4.2.2 on 2024-02-26 06:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Weather_API", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
