# Generated by Django 4.2.2 on 2024-02-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Weather_API", "0002_weatherdata_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherdata",
            name="temperature",
            field=models.CharField(max_length=30),
        ),
    ]
